# Generated by Django 2.1.1 on 2019-05-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(max_length=50)),
                ('receptor', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(max_digits=8, decimal_places=2)),
                ('motivo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
